### ISSUE TITLE
[Issue] panic: runtime error: index out of range [2] with length 2

### ISSUE THREAD

**Issue by gy741** [projectdiscovery/subfinder#1075]
**Describe the bug**

Hello,

The following error occurs when using the default subdomain as input.

```
panic: runtime error: index out of range [2] with length 2

goroutine 537 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/redhuntlabs.(*Source).Run.func1()
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/redhuntlabs/redhuntlabs.go:53 +0xd7b
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/redhuntlabs.(*Source).Run
        /home/runner/work/subfinder/subfinder/v2/pkg/subscraping/sources/redhuntlabs/redhuntlabs.go:39 +0x12d
```

Thanks.

**Subfinder version**

```
[INF] Current Version: v2.6.3
```

**Complete command you used to reproduce this**

Primary subdomains exist in the subdomain.txt file.

Ex) dev.example.com

```
subfinder -dL subdomain.txt -o subdomain_2.txt -all -v
```

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
