### ISSUE TITLE
Unexpected Panic error in subfinder

### ISSUE THREAD

**Issue by sanjai-AK47** [projectdiscovery/subfinder#1160]
Hell when I was testing performance subfinder each resources I faced panic error and the full error was : 
```code
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd57b8a]

goroutine 66 [running]:
github.com/projectdiscovery/ratelimit.(*MultiLimiter).Stop(0x56240f?, {0x0?, 0xc000e1be01?, 0x16a75a0?})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.26/keyratelimit.go:106 +0x2a
github.com/projectdiscovery/subfinder/v2/pkg/subscraping.(*Session).Close(0xc000386780)
	/home/runner/work/subfinder/subfinder/v2/pkg/subscraping/agent.go:128 +0x26
github.com/projectdiscovery/subfinder/v2/pkg/passive.(*Agent).EnumerateSubdomainsWithCtx.func1()
	/home/runner/work/subfinder/subfinder/v2/pkg/passive/passive.go:77 +0x60e
created by github.com/projectdiscovery/subfinder/v2/pkg/passive.(*Agent).EnumerateSubdomainsWithCtx in goroutine 1
	/home/runner/work/subfinder/subfinder/v2/pkg/passive/passive.go:37 +0x185

```
and also Im not well in golang but when I tested the performance with my [tool](https://github.com/sanjai-AK47/Subdominator) with subfinder and specially with resources I faced this error and after researching about this error I think it occurs when it try to read or write to the unallocated memory address and to analyze and handle this error I think the recover() built-in Go function will be helpfull and Im also attaching a screenshot about the error :

![image](https://github.com/projectdiscovery/subfinder/assets/119435129/48787fa4-8632-4b1b-ba06-94fbb4a2b0b1)

Kind regards,
[MR.Z](https://github.com/sanjai-AK47)

**Comment by vprg888** [comment]
![Uploading Screenshot 2024-02-24 165858.png…]()

**Comment by vprg888** [comment]
![Screenshot 2024-02-24 165858](https://github.com/projectdiscovery/subfinder/assets/154678902/a8bfb717-5356-4596-b837-3f97fbdf4002)

**Comment by Shervin78** [comment]
oh my god this my problem help please?
