### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd8fa75]

### ISSUE THREAD

**Issue by vprg888** [projectdiscovery/subfinder#1168]
**Hello... How to fix this?**

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd8fa75]

goroutine 75 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run.func1()
        github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:36 +0x255
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus.(*Source).Run in goroutine 49
        github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/digitorus/digitorus.go:28 +0x10d

**Comment by dogancanbakir** [comment]
We'd love to assist you in the best possible way! To make that happen, kindly fill out all the required fields. 

```
<!-- 
1. Please search to see if an issue already exists for the bug you encountered.
2. For support requests, FAQs or "How to" questions, please use the GitHub Discussions section instead - https://github.com/projectdiscovery/subfinder/discussions or
3. Join our discord server at https://discord.gg/projectdiscovery and post the question on the #subfinder channel.
-->

<!-- ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION. -->

### Subfinder version:
<!-- You can find current version of subfinder with "subfinder -version" -->
<!-- We only accept issues that are reproducible on the latest version of subfinder. -->
<!-- You can find the latest version of project at https://github.com/projectdiscovery/subfinder/releases/ -->

### Current Behavior:
<!-- A concise description of what you're experiencing. -->

### Expected Behavior:
<!-- A concise description of what you expected to happen. -->

### Steps To Reproduce:
<!--
Example: steps to reproduce the behavior:
1. Run 'subfinder ..'
2. See error...
-->


### Anything else:
<!-- Links? References? Screnshots? Anything that will give us more context about the issue that you are encountering! -->

```
