### ISSUE TITLE
[Issue] Errors With the Hunter Source

### ISSUE THREAD

**Issue by Bundy01** [projectdiscovery/subfinder#1390]
**Describe the bug**
Unable to use source despite adding API key

```
[DBG] Selected source(s) for this search: 
[INF] Enumerating subdomains for amp-endpoint1.com
[WRN] Could not get wildcards for domain amp-endpoint1.com: amp-endpoint1.com is not a wildcard domain
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd635ea]

goroutine 53 [running]:
github.com/projectdiscovery/ratelimit.(*MultiLimiter).Stop(0x56260f?, {0x0?, 0xc0008b7e01?, 0x16b7180?})
	/home/runner/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.34/keyratelimit.go:106 +0x2a
github.com/projectdiscovery/subfinder/v2/pkg/subscraping.(*Session).Close(0xc000398a60)
	/home/runner/work/subfinder/subfinder/v2/pkg/subscraping/agent.go:128 +0x26
github.com/projectdiscovery/subfinder/v2/pkg/passive.(*Agent).EnumerateSubdomainsWithCtx.func1()
	/home/runner/work/subfinder/subfinder/v2/pkg/passive/passive.go:77 +0x60e
created by github.com/projectdiscovery/subfinder/v2/pkg/passive.(*Agent).EnumerateSubdomainsWithCtx in goroutine 1
	/home/runner/work/subfinder/subfinder/v2/pkg/passive/passive.go:37 +0x185

```

**Subfinder version**
2.6.6

**Complete command you used to reproduce this**
`subfinder -nW -d amp-endpoint1.com -s hunter -v`

**Screenshots**
Add screenshots of the error for a better context.

**Comment by Bundy01** [comment]
Sorry, it's a local error.

**Comment by dogancanbakir** [comment]
@Bundy01 What do you mean by local error? I still expect you shouldn't get a nil deref error.

**Comment by Bundy01** [comment]
I made an alias of the command for limited sources, hence the error I posted.
```sh
alias subless='subfinder -es binaryedge,hunter,securitytrails'
```

The real command was `subfinder -es binaryedge,hunter,securitytrails -nW -d amp-endpoint1.com -s hunter -v`.

I'm getting an error with this source by enabling `stats: true` in the conf file, but it's due to a blocklist I'm using.

**Comment by dogancanbakir** [comment]
Thanks, will look into it.
