### ISSUE TITLE
index out of range in redhuntlabs

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/subfinder#1448]
```console
panic: runtime error: index out of range [2] with length 2

goroutine 1406 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/redhuntlabs.(*Source).Run.func1()
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.6.6/pkg/subscraping/sources/redhuntlabs/redhuntlabs.go:53 +0xd3b
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/redhuntlabs.(*Source).Run in goroutine 1352
	/layers/google.go.functions-framework/gopath/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.6.6/pkg/subscraping/sources/redhuntlabs/redhuntlabs.go:39 +0x129

```
reported by @Ice3man543

**Comment by dogancanbakir** [comment]
This is fixed in v2.6.7. Closing.
