### ISSUE TITLE
[Issue] invalid memory address with sitedossier source

### ISSUE THREAD

**Issue by team-projectdiscovery** [projectdiscovery/subfinder#347]
**Describe the bug**

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7d0532]

goroutine 79 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(agent).enumerate(0xc00011f240, 0xa208a0, 0xc000060900, 0xc00002a480, 0x38)
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.5/pkg/subscraping/sources/sitedossier/sitedossier.go:40 +0x192
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(Source).Run.func1(0xc00011f240, 0xa208a0, 0xc000060900, 0x7fffc2cb9701, 0x10)        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.5/pkg/subscraping/sources/sitedossier/sitedossier.go:73 +0xc6
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run
        /root/go/pkg/mod/github.com/projectdiscovery/subfinder/v2@v2.4.5/pkg/subscraping/sources/sitedossier/sitedossier.go:72 +0xc5
```

**Subfinder version**
 2.4.5

**Comment by team-projectdiscovery** [comment]
This is fixed in the dev branch with https://github.com/projectdiscovery/subfinder/pull/352 @vzamanillo ❤️
