### ISSUE TITLE
[Issue] segfaulty with sitedossier

### ISSUE THREAD

**Issue by tech-ozon-io** [projectdiscovery/subfinder#358]
**Describe the bug**
I encounter this backtrace:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7d1532]

goroutine 77 [running]:
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*agent).enumerate(0xc000171190, 0xa25080, 0xc00005f020, 0xc000028400, 0x39)
	/home/thierry/domains-fr/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:40 +0x192
github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run.func1(0xc000171190, 0xa25080, 0xc00005f020, 0x7fff6df16e76, 0x11)
	/home/thierry/domains-fr/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:73 +0xc6
created by github.com/projectdiscovery/subfinder/v2/pkg/subscraping/sources/sitedossier.(*Source).Run
	/home/thierry/domains-fr/subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go:72 +0xc5
```

**Subfinder version**
current master at 01/02/2020

**Problem**

in the file subfinder/v2/pkg/subscraping/sources/sitedossier/sitedossier.go

```
	resp, err := a.session.SimpleGet(ctx, baseURL)
	isnotfound := resp != nil && resp.StatusCode == http.StatusNotFound
1>	if err != nil && !isnotfound {
		a.results <- subscraping.Result{Source: "sitedossier", Type: subscraping.Error, Error: err}
		a.session.DiscardHTTPResponse(resp)
	}

2>	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		a.results <- subscraping.Result{Source: "sitedossier", Type: subscraping.Error, Error: err}
		resp.Body.Close()
	}
	resp.Body.Close()
```

I think that when error is process at "1>", it miss something like return or some process abort because the step "2>" is executed using "resp.Body" which is nil, and trigger a segfault.

Thierry

**Comment by bauthard** [comment]
Hi @tech-ozon-io,

This issue is fixed in this PR https://github.com/projectdiscovery/subfinder/pull/352 merged into `dev` branch.

**Comment by tech-ozon-io** [comment]
thanks 👍

**Comment by Mzack9999** [comment]
Closing as the issue has been addressed in the dev branch
