### ISSUE TITLE
[Issue] Bug : Subfinder : Crash on startup.

### ISSUE THREAD

**Issue by Rbcafe** [projectdiscovery/subfinder#966]
**Bug**

Crash on startup.

**Subfinder version**

2.62

**Go version**

go version go1.21.0 linux/arm.

**Go Installation (snap)**

go      1.21.0     10325  latest/stable  canonical✓  classic.

**Complete command you used to reproduce this**

subfinder

**System**

Linux R1 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux. (Raspberry).

**Logs**

```
runtime: g 1: unexpected return pc for runtime.main called from 0x1
stack: frame={sp:0x1cefeb8, fp:0x1ceff04} stack=[0x1cee000,0x1cf0000)
0x01cefe38:  0x01785c08  0x00000000  0x00053754 <runtime.runOpenDeferFrame+0x000001bc>  0x01cefdd8 
0x01cefe48:  0x00000100  0x00c99534 <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000f8>  0x00d42d90  0x01785c08 
0x01cefe58:  0x20080522  0x000066de  0x00000000  0x00000000 
0x01cefe68:  0x00002000  0x01c02100  0x00000000  0x00000000 
0x01cefe78:  0x0110547c  0x00c99534 <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000f8>  0x000575f8 <runtime.main+0x00000434>  0x01c82500 
0x01cefe88:  0x00000100  0x01c82580  0x00199008 <math/big.(*Float).Text+0x00000054>  0x00000015 
0x01cefe98:  0x00000000  0x00021618 <runtime.mallocgc+0x0000012c>  0x00000015  0x01c80240 
0x01cefea8:  0x00000240  0x00000000  0x00000000  0x00000100 
0x01cefeb8: <0x00000001  0x00021618 <runtime.mallocgc+0x0000012c>  0x00000000  0x00240000 <archive/zip.headerFileInfo.ModTime+0x0000014c> 
0x01cefec8:  0x00021618 <runtime.mallocgc+0x0000012c>  0x000ff5c8 <io/fs.globWithLimit+0x00000170>  0x00000080  0x00000000 
0x01cefed8:  0x00000000  0x00000000  0x00000000  0x00000000 
0x01cefee8:  0x00000000  0x00000000  0x00000000  0x00000000 
0x01cefef8:  0xb6d99510  0xb6d8d2e0  0x00000100 >0x017cd508 
0x01ceff08:  0x01c82500  0x00000000  0x000610dc <runtime.malg+0x0000001c>  0x000000fc 
0x01ceff18:  0x00059978 <runtime.casgstatus+0x00000354>  0x017cdd10  0x00000001  0x00000000 
0x01ceff28:  0x00000001  0x00000000  0x000885b0 <runtime.exitsyscall+0x00000134>  0x017cdd10 
0x01ceff38:  0x00000000  0x00000000  0x01c35301  0x00000002 
0x01ceff48:  0x00000000  0x00000000  0x00000000  0x00000000 
0x01ceff58:  0x01c3e760  0x00060390 <runtime.reentersyscall+0x000001b4>  0x00088478 <runtime.entersyscall+0x00000018>  0x01c02148 
0x01ceff68:  0x00018b14 <runtime.cgocall+0x000000a0>  0x01c02100  0x00000003  0x00000002 
0x01ceff78:  0x01c02100  0x01c35300  0x00018ac4 <runtime.cgocall+0x00000050> 
fatal error: unknown caller pc

runtime stack:
runtime.throw({0xe44006, 0x11})
	/snap/go/10325/src/runtime/panic.go:1077 +0x4c fp=0xbe8f74a4 sp=0xbe8f7490 pc=0x5425c
runtime.(*unwinder).next(0xbe8f7510)
	/snap/go/10325/src/runtime/traceback.go:465 +0x36c fp=0xbe8f74f4 sp=0xbe8f74a4 pc=0x7d0d8
runtime.addOneOpenDeferFrame.func1()
	/snap/go/10325/src/runtime/panic.go:648 +0x78 fp=0xbe8f7618 sp=0xbe8f74f4 pc=0x5330c
runtime.systemstack()
	/snap/go/10325/src/runtime/asm_arm.s:317 +0x60 fp=0xbe8f761c sp=0xbe8f7618 pc=0x8a8a8

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/snap/go/10325/src/runtime/asm_arm.s:274 +0x4 fp=0x1cefd2c sp=0x1cefd28 pc=0x8a83c
runtime.addOneOpenDeferFrame(0x1c02100, 0x0, 0x0)
	/snap/go/10325/src/runtime/panic.go:645 +0x70 fp=0x1cefd48 sp=0x1cefd2c pc=0x5327c
panic({0xd42d90, 0x1785c08})
	/snap/go/10325/src/runtime/panic.go:916 +0x284 fp=0x1cefd9c sp=0x1cefd48 pc=0x53c44
runtime.panicmem(...)
	/snap/go/10325/src/runtime/panic.go:261
runtime.sigpanic()
	/snap/go/10325/src/runtime/signal_unix.go:861 +0x39c fp=0x1cefdcc sp=0x1cefd9c pc=0x6e618
runtime.deferCallSave(0x1cefe30, 0x100)
	/snap/go/10325/src/runtime/panic.go:798 +0x88 fp=0x1cefdd8 sp=0x1cefdd0 pc=0x5393c
runtime.runOpenDeferFrame(0x1c965a0)
	/snap/go/10325/src/runtime/panic.go:771 +0x1bc fp=0x1cefdf8 sp=0x1cefdd8 pc=0x53754
panic({0xd42d90, 0x1785c08})
	/snap/go/10325/src/runtime/panic.go:914 +0x244 fp=0x1cefe4c sp=0x1cefdf8 pc=0x53c04
runtime.panicmem(...)
	/snap/go/10325/src/runtime/panic.go:261
runtime.sigpanic()
	/snap/go/10325/src/runtime/signal_unix.go:861 +0x39c fp=0x1cefe7c sp=0x1cefe4c pc=0x6e618
github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw()
	/home/pi/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.49/permission/permission_linux.go:40 +0xf8 fp=0x1cefeb8 sp=0x1cefe80 pc=0xc99534
runtime.doInit(...)
	/snap/go/10325/src/runtime/proc.go:6707
runtime.main()
	/snap/go/10325/src/runtime/proc.go:249 +0x434 fp=0x1ceff04 sp=0x1cefeb8 pc=0x575f8
runtime: g 1: unexpected return pc for runtime.main called from 0x1
stack: frame={sp:0x1cefeb8, fp:0x1ceff04} stack=[0x1cee000,0x1cf0000)
0x01cefe38:  0x01785c08  0x00000000  0x00053754 <runtime.runOpenDeferFrame+0x000001bc>  0x01cefdd8 
0x01cefe48:  0x00000100  0x00c99534 <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000f8>  0x00d42d90  0x01785c08 
0x01cefe58:  0x20080522  0x000066de  0x00000000  0x00000000 
0x01cefe68:  0x00002000  0x01c02100  0x00000000  0x00000000 
0x01cefe78:  0x0110547c  0x00c99534 <github.com/projectdiscovery/utils/permission.checkCurrentUserCapNetRaw+0x000000f8>  0x000575f8 <runtime.main+0x00000434>  0x01c82500 
0x01cefe88:  0x00000100  0x01c82580  0x00199008 <math/big.(*Float).Text+0x00000054>  0x00000015 
0x01cefe98:  0x00000000  0x00021618 <runtime.mallocgc+0x0000012c>  0x00000015  0x01c80240 
0x01cefea8:  0x00000240  0x00000000  0x00000000  0x00000100 
0x01cefeb8: <0x00000001  0x00021618 <runtime.mallocgc+0x0000012c>  0x00000000  0x00240000 <archive/zip.headerFileInfo.ModTime+0x0000014c> 
0x01cefec8:  0x00021618 <runtime.mallocgc+0x0000012c>  0x000ff5c8 <io/fs.globWithLimit+0x00000170>  0x00000080  0x00000000 
0x01cefed8:  0x00000000  0x00000000  0x00000000  0x00000000 
0x01cefee8:  0x00000000  0x00000000  0x00000000  0x00000000 
0x01cefef8:  0xb6d99510  0xb6d8d2e0  0x00000100 >0x017cd508 
0x01ceff08:  0x01c82500  0x00000000  0x000610dc <runtime.malg+0x0000001c>  0x000000fc 
0x01ceff18:  0x00059978 <runtime.casgstatus+0x00000354>  0x017cdd10  0x00000001  0x00000000 
0x01ceff28:  0x00000001  0x00000000  0x000885b0 <runtime.exitsyscall+0x00000134>  0x017cdd10 
0x01ceff38:  0x00000000  0x00000000  0x01c35301  0x00000002 
0x01ceff48:  0x00000000  0x00000000  0x00000000  0x00000000 
0x01ceff58:  0x01c3e760  0x00060390 <runtime.reentersyscall+0x000001b4>  0x00088478 <runtime.entersyscall+0x00000018>  0x01c02148 
0x01ceff68:  0x00018b14 <runtime.cgocall+0x000000a0>  0x01c02100  0x00000003  0x00000002 
0x01ceff78:  0x01c02100  0x01c35300  0x00018ac4 <runtime.cgocall+0x00000050> 

goroutine 2 [force gc (idle)]:
runtime.gopark(0xf6420c, 0x17cbaf0, 0x11, 0x14, 0x1)
	/snap/go/10325/src/runtime/proc.go:398 +0x104 fp=0x1c3efd4 sp=0x1c3efc0 pc=0x57a94
runtime.goparkunlock(...)
	/snap/go/10325/src/runtime/proc.go:404
runtime.forcegchelper()
	/snap/go/10325/src/runtime/proc.go:322 +0xe4 fp=0x1c3efec sp=0x1c3efd4 pc=0x578d0
runtime.goexit()
	/snap/go/10325/src/runtime/asm_arm.s:859 +0x4 fp=0x1c3efec sp=0x1c3efec pc=0x8c4e8
created by runtime.init.5 in goroutine 1
	/snap/go/10325/src/runtime/proc.go:310 +0x1c

goroutine 18 [GC sweep wait]:
runtime.gopark(0xf6420c, 0x17cc308, 0xc, 0x14, 0x1)
	/snap/go/10325/src/runtime/proc.go:398 +0x104 fp=0x1c3a7c4 sp=0x1c3a7b0 pc=0x57a94
runtime.goparkunlock(...)
	/snap/go/10325/src/runtime/proc.go:404
runtime.bgsweep(0x1c8e000)
	/snap/go/10325/src/runtime/mgcsweep.go:280 +0xa8 fp=0x1c3a7e4 sp=0x1c3a7c4 pc=0x3f980
runtime.gcenable.func1()
	/snap/go/10325/src/runtime/mgc.go:200 +0x28 fp=0x1c3a7ec sp=0x1c3a7e4 pc=0x2fffc
runtime.goexit()
	/snap/go/10325/src/runtime/asm_arm.s:859 +0x4 fp=0x1c3a7ec sp=0x1c3a7ec pc=0x8c4e8
created by runtime.gcenable in goroutine 1
	/snap/go/10325/src/runtime/mgc.go:200 +0x74

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xf6420c, 0x17ccaf8, 0xd, 0x14, 0x2)
	/snap/go/10325/src/runtime/proc.go:398 +0x104 fp=0x1c3afb4 sp=0x1c3afa0 pc=0x57a94
runtime.goparkunlock(...)
	/snap/go/10325/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x17ccaf8)
	/snap/go/10325/src/runtime/mgcscavenge.go:425 +0x68 fp=0x1c3afc8 sp=0x1c3afb4 pc=0x3cbb8
runtime.bgscavenge(0x1c8e000)
	/snap/go/10325/src/runtime/mgcscavenge.go:653 +0x3c fp=0x1c3afe4 sp=0x1c3afc8 pc=0x3d2d4
runtime.gcenable.func2()
	/snap/go/10325/src/runtime/mgc.go:201 +0x28 fp=0x1c3afec sp=0x1c3afe4 pc=0x2ffa8
runtime.goexit()
	/snap/go/10325/src/runtime/asm_arm.s:859 +0x4 fp=0x1c3afec sp=0x1c3afec pc=0x8c4e8
created by runtime.gcenable in goroutine 1
	/snap/go/10325/src/runtime/mgc.go:201 +0xbc

goroutine 20 [finalizer wait]:
runtime.gopark(0xf640ac, 0x17e169c, 0x10, 0x14, 0x1)
	/snap/go/10325/src/runtime/proc.go:398 +0x104 fp=0x1c3b788 sp=0x1c3b774 pc=0x57a94
runtime.runfinq()
	/snap/go/10325/src/runtime/mfinal.go:193 +0x110 fp=0x1c3b7ec sp=0x1c3b788 pc=0x2ee5c
runtime.goexit()
	/snap/go/10325/src/runtime/asm_arm.s:859 +0x4 fp=0x1c3b7ec sp=0x1c3b7ec pc=0x8c4e8
created by runtime.createfing in goroutine 1
	/snap/go/10325/src/runtime/mfinal.go:163 +0x5c

```

**Screenshots**

![stack](https://github.com/projectdiscovery/subfinder/assets/2713634/2bec3e8d-e26b-4bda-af52-5eb183096816)

Best regards.
@rbcafe

**Comment by lubangakeneaaron** [comment]
I have the same issue

**Comment by dogancanbakir** [comment]
@lubangakeneaaron,
This issue, hopefully, will be fixed with the new release -the fix merged into the dev branch and hopefully will be released soon.
